import type { CfgSchema } from './parser.js';

export const item_schema: CfgSchema = {
    trigger: 'Item',
    end_marker: '[ENDITEMLIST]',
    fields: [
        { name: 'id',                    type: 'int' },
        { name: 'name',                  type: 'string' },
        { name: 'type',                  type: 'int' },
        { name: 'equip_pos',             type: 'int' },
        { name: 'effect_type',           type: 'int' },
        { name: 'effect_value1',         type: 'int' },
        { name: 'effect_value2',         type: 'int' },
        { name: 'effect_value3',         type: 'int' },
        { name: 'effect_value4',         type: 'int' },
        { name: 'effect_value5',         type: 'int' },
        { name: 'effect_value6',         type: 'int' },
        { name: 'durability',            type: 'int' },
        { name: 'special_effect',        type: 'int' },
        { name: 'sprite',                type: 'int' },
        { name: 'sprite_frame',          type: 'int' },
        { name: 'price',                 type: 'price' },
        { name: 'weight',                type: 'int' },
        { name: 'appr_value',            type: 'int' },
        { name: 'speed',                 type: 'int' },
        { name: 'level_limit',           type: 'int' },
        { name: 'gender_limit',          type: 'int' },
        { name: 'special_effect_value1', type: 'int' },
        { name: 'special_effect_value2', type: 'int' },
        { name: 'related_skill',         type: 'int' },
        { name: 'category',              type: 'int' },
        { name: 'item_color',            type: 'int' },
    ],
};

export const npc_schema: CfgSchema = {
    trigger: 'Npc',
    fields: [
        { name: 'name',                type: 'string' },
        { name: 'sprite_id',           type: 'int' },
        { name: 'hit_dice',            type: 'int' },
        { name: 'defense_ratio',       type: 'int' },
        { name: 'hit_ratio',           type: 'int' },
        { name: 'min_bravery',         type: 'int' },
        { name: 'exp_dice',            type: 'int' },
        { name: 'attack_dice',         type: 'int' },
        { name: 'attack_sides',        type: 'int' },
        { name: 'size',                type: 'int' },
        { name: 'side',                type: 'int' },
        { name: 'action_limit',        type: 'int' },
        { name: 'action_time',         type: 'int' },
        { name: 'resist_magic',        type: 'int' },
        { name: 'magic_level',         type: 'int' },
        { name: 'day_of_week',         type: 'int' },
        { name: 'chat_msg',            type: 'int' },
        { name: 'target_search_range', type: 'int' },
        { name: 'regen_time',          type: 'int' },
        { name: 'attribute',           type: 'int' },
        { name: 'abs_damage',          type: 'int' },
        { name: 'max_mana',            type: 'int' },
        { name: 'magic_hit_ratio',     type: 'int' },
        { name: 'attack_range',        type: 'int' },
    ],
};

export const magic_schema: CfgSchema = {
    trigger: 'magic',
    fields: [
        { name: 'id',         type: 'int' },
        { name: 'name',       type: 'string' },
        { name: 'type',       type: 'int' },
        { name: 'delay',      type: 'int' },
        { name: 'duration',   type: 'int' },
        { name: 'mana_cost',  type: 'int' },
        { name: 'range1',     type: 'int' },
        { name: 'range2',     type: 'int' },
        { name: 'e1_dice',    type: 'int' },
        { name: 'e1_sides',   type: 'int' },
        { name: 'e1_bonus',   type: 'int' },
        { name: 'e2_dice',    type: 'int' },
        { name: 'e2_sides',   type: 'int' },
        { name: 'e2_bonus',   type: 'int' },
        { name: 'e3_dice',    type: 'int' },
        { name: 'e3_sides',   type: 'int' },
        { name: 'e3_bonus',   type: 'int' },
        { name: 'int_req',    type: 'int' },
        { name: 'cost',       type: 'int' },
        { name: 'category',   type: 'int' },
        { name: 'attribute',  type: 'int' },
    ],
};

export const skill_schema: CfgSchema = {
    trigger: 'skill',
    fields: [
        { name: 'id',     type: 'int' },
        { name: 'name',   type: 'string' },
        { name: 'type',   type: 'int' },
        { name: 'value1', type: 'int' },
        { name: 'value2', type: 'int' },
        { name: 'value3', type: 'int' },
        { name: 'value4', type: 'int' },
        { name: 'value5', type: 'int' },
        { name: 'value6', type: 'int' },
    ],
};

export const quest_schema: CfgSchema = {
    trigger: 'quest',
    fields: [
        { name: 'id',                 type: 'int' },
        { name: 'side',               type: 'int' },
        { name: 'type',               type: 'int' },
        { name: 'target_type',        type: 'int' },
        { name: 'max_count',          type: 'int' },
        { name: 'from_id',            type: 'int' },
        { name: 'min_level',          type: 'int' },
        { name: 'max_level',          type: 'int' },
        { name: 'req_skill',          type: 'int' },
        { name: 'req_skill_pct',      type: 'int' },
        { name: 'time_limit',         type: 'int' },
        { name: 'assign_type',        type: 'int' },
        { name: 'reward_type1',       type: 'int' },
        { name: 'reward_amount1',     type: 'int' },
        { name: 'reward_type2',       type: 'int' },
        { name: 'reward_amount2',     type: 'int' },
        { name: 'reward_type3',       type: 'int' },
        { name: 'reward_amount3',     type: 'int' },
        { name: 'contribution',       type: 'int' },
        { name: 'contribution_limit', type: 'int' },
        { name: 'resp_mode',          type: 'int' },
        { name: 'map',                type: 'string' },
        { name: 'x',                  type: 'int' },
        { name: 'y',                  type: 'int' },
        { name: 'range',              type: 'int' },
        { name: 'quest_id',           type: 'int' },
        { name: 'req_contribution',   type: 'int' },
    ],
};

export const crusade_schema: CfgSchema = {
    trigger: 'crusade-structure',
    fields: [
        { name: 'id',       type: 'int' },
        { name: 'map_name', type: 'string' },
        { name: 'type',     type: 'int' },
        { name: 'x',        type: 'int' },
        { name: 'y',        type: 'int' },
    ],
};

// BuildItem: 6 ingredient triples (item_id, count, value), 0 = empty
export const build_schema: CfgSchema = {
    trigger: 'BuildItem',
    fields: [
        { name: 'result',       type: 'string' },
        { name: 'skill_limit',  type: 'int' },
        { name: 'i0_id',        type: 'int' }, { name: 'i0_count', type: 'int' }, { name: 'i0_value', type: 'int' },
        { name: 'i1_id',        type: 'int' }, { name: 'i1_count', type: 'int' }, { name: 'i1_value', type: 'int' },
        { name: 'i2_id',        type: 'int' }, { name: 'i2_count', type: 'int' }, { name: 'i2_value', type: 'int' },
        { name: 'i3_id',        type: 'int' }, { name: 'i3_count', type: 'int' }, { name: 'i3_value', type: 'int' },
        { name: 'i4_id',        type: 'int' }, { name: 'i4_count', type: 'int' }, { name: 'i4_value', type: 'int' },
        { name: 'i5_id',        type: 'int' }, { name: 'i5_count', type: 'int' }, { name: 'i5_value', type: 'int' },
        { name: 'average_value', type: 'int' },
        { name: 'max_skill',     type: 'int' },
        { name: 'attribute',     type: 'int' },
    ],
};

export const potion_schema: CfgSchema = {
    trigger: 'potion',
    fields: [
        { name: 'id',         type: 'int' },
        { name: 'result',     type: 'string' },
        { name: 'i0_id',      type: 'int' }, { name: 'i0_count', type: 'int' },
        { name: 'i1_id',      type: 'int' }, { name: 'i1_count', type: 'int' },
        { name: 'i2_id',      type: 'int' }, { name: 'i2_count', type: 'int' },
        { name: 'i3_id',      type: 'int' }, { name: 'i3_count', type: 'int' },
        { name: 'i4_id',      type: 'int' }, { name: 'i4_count', type: 'int' },
        { name: 'i5_id',      type: 'int' }, { name: 'i5_count', type: 'int' },
        { name: 'skill_limit', type: 'int' },
        { name: 'difficulty',  type: 'int' },
    ],
};
